name: Build On Push

on:
  workflow_call:
    inputs:
      github-event-action:
        type: string
        required: true
    secrets:
      GPG_SIGNING_KEY:
        required: true
      GPG_SIGNING_PASSPHRASE:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
           distribution: adopt
           java-version: 8
           java-package: jdk
           cache: 'gradle'
           
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"
            
      - name: Run Gradle Build
        run: ./gradlew -Pgithub.event.action=${{inputs.github-event-action}} dependencyReport build
            
      - name: Try signing
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        run: ./gradlew -Pgithub.event.action=${{inputs.github-event-action}} signMavenJavaPublication
            
      - name: Store Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: "**/build/reports/project/dependencies.txt"

      - name: Store HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html
          path: "**/reports/tests/"
          if-no-files-found: ignore

      - name: Store XML test report
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: "**/test-results/"
          if-no-files-found: ignore

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/test-results/**/*.xml"
